# Site settings
title: WalletWiz
description: >- # this means to ignore newlines until "baseurl:"
  'WalletWiz is all about one thing: Financial Literacy.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
